config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do

    # resources :time_tracks, only: [:index, :create, :update]
    post 'time_tracks', to: 'time_tracks#create'
    put 'time_tracks', to: 'time_tracks#update_last'

    concern :list_conversation_objects do |options|
      resources :conversation_objects, options.merge(only: [:index])
    end

    concern :unseen_objects do |options|
      delete 'unseen_objects', to: 'unseen_objects#destroy_all', defaults: options
      get 'unseen_objects', to: 'unseen_objects#index', defaults: options
      # resources :unseen_objects, options.merge(only: [:destroy_all])
    end

    concern :attachments do |options|
      resources :attachments, options.merge(only: [:new, :create])
    end

    resources :attachments, only: [:update]

    
    resources :organizations, shallow: true do
      concerns :unseen_objects, parent_type: 'Organization'

      resources :conversations do
        resources :agenda_items, only: [:index]
        concerns :list_conversation_objects, parent_type: 'Conversation'
        concerns :unseen_objects, parent_type: 'Conversation'
        concerns :attachments, parent_type: 'Conversation'
      end

      resources :organization_members, only: [:index, :create, :destroy]
    end

    resources :agenda_items, only: [:create, :show, :update] do
      concerns :list_conversation_objects, parent_type: 'AgendaItem'
      concerns :unseen_objects, parent_type: 'AgendaItem'
      concerns :attachments, parent_type: 'AgendaItem'
    end

    resources :deliverables, only: [:create, :show, :update] do
      concerns :list_conversation_objects, parent_type: 'Deliverable'
      concerns :unseen_objects, parent_type: 'Deliverable'
      concerns :attachments, parent_type: 'Deliverable'
    end

    resources :comments
    resources :conversation_members, only: [:create, :destroy]
    resources :organization_members, only: [:create, :update, :destroy]
    resources :meetings, only: [:create]
    resources :users, only: [:index, :create, :update], shallow: true do
      concerns :unseen_objects, parent_type: 'User'
    end
    resources :conversations, only: [:create, :update, :destroy]
    devise_scope :user do
      resources :session_tokens, only: [:create, :show]
      resources :long_lived_tokens, only: [:create]
    end
    resources :devices, only: [:create, :update]
  end

  resources :attachments, only: [:show]

  resources :organizations, shallow: true do
    resources :organization_members, only: [:index, :destroy]
    resources :conversations
  end

  get 'agenda_items/:id', to: 'react_routes#index', as: :agenda_item
  get 'deliverables/:id', to: 'react_routes#index', as: :deliverable
  get 'signup', to: 'react_routes#new_registration', as: :signup
  get 'organizations/:id/settings', to: 'react_routes#index', as: :settings
  get 'api/organizations/shallow/:id', to: 'api/organizations#show_only_organization'

  # Old routes are redirected to new shallow routes
  get 'conversations/:id/agenda_items/:agenda_item_id/deliverables/:deliverable_id', to: redirect('/deliverables/%{deliverable_id}')
  get 'conversations/:id/agenda_items/:agenda_item_id', to: redirect('/agenda_items/%{agenda_item_id}')

  # Route each error code to it's respective action in ErrorsController
  match '/404', :to => 'errors#not_found', :via => :all
  match '/422', :to => 'errors#unacceptable', :via => :all
  match '/500', :to => 'errors#internal_error', :via => :all

  devise_for :users, controllers: {
                       registrations: 'users/registrations',
                       sessions:      'users/sessions',
                       invitations:   'users/invitations'
                   }
  resources :samples, only: [:index]

  resources :apidocs, only: [:index]
  
  authenticated :user do
    root to: 'organizations#index', as: :authenticated_root
  end

  authenticate :user, lambda { |u| u.email == 'gugl@guenterglueck.com' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/websocket', to: ActionCable.server, via: [:get, :post]

  # root 'landing_page#index'
  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  include Archival
  
  belongs_to :owner, class_name: 'User'
  has_many :organization_members, dependent: :destroy
  has_many :members, through: :organization_members
  has_many :conversations, dependent: :destroy
  has_many :agenda_items, through: :conversations
  has_many :deliverables, through: :agenda_items
  has_many :comments, through: :members
  has_many :unseen_objects, dependent: :destroy

  validates_presence_of :name

  DEFAULT_NAME = 'Default Organization Name'

  after_create :add_default_conversation

  def add_default_conversation
    conversation = conversations.create!(title: Conversation::DEFAULT_TITLE)
    conversation.conversation_members.create!(member: owner)
  end

  def to_s
    name
  end

end

app/controllers/api/organizations_controller.rb
module Api
  class OrganizationsController < Base
    before_filter :authenticate_user!
    before_action :set_organization, only: [:update]
    after_action :verify_authorized,    except: :index
    after_action :verify_policy_scoped, only: :index

    respond_to :json

    include Swagger::Blocks

    swagger_path '/organizations' do
      operation :get, security: [bearer: []] do
        key :summary, 'List organizations'
        key :description, 'Returns the list of organizations the user is a member of'
        key :operationId, 'listOrganizations'
        key :tags, ['organization']
        key :produces, ['application/json']
        
        response 200 do
          key :description, 'An array of organizations'
          schema do
            key :'$ref', :responseMany_Organization
          end
        end
        response :default do
          key :description, 'Unexpected error'
        end
      end
    end
    
    # GET /organizations.json
    def index
      @organizations = policy_scope(Organization)
      render json: @organizations
    end
    
    swagger_path '/organizations/{id}' do
      operation :get, security: [bearer: []] do
        key :summary, 'Details for a specific Organization'
        key :description, 'Returns the all details for the organization overview'
        key :operationId, 'findOrganizationById'
        key :tags, ['organization']
        key :produces, ['application/json']

        parameter name: :id, in: :path, type: :string, required: true
        
        response 200 do
          key :description, 'Organization response'
          schema do
            key :'$ref', :responseOne_Organization
          end
        end
        response :default do
          key :description, 'Unexpected error'
        end
      end
    end

    # TODO: Add filters so that the frontend can decide to only get a minimal set of data
    #       At the moment we are sending way to much stuff down the wire.
    # GET /organizations/1.json
    def show
      # TODO: Remove that workaround when we switch to the final ActionCable release and can use connection-tokens
      # to build a list of connected connections per user and don't track the user as offline when he closes one of
      # his multiple browser windows. Then we can also remove that workaround.
      current_user.update presence_status: 'online'
      @organization = policy_scope(Organization).includes(organization_members: :member).find(params[:id])
      authorize @organization
      current_user.update last_visited_organization: @organization

      @conversations = policy_scope(Conversation)
                       .where(organization: @organization)
                       .includes(:agenda_items, :deliverables, :agenda_item_deliverables, :conversation_members, :members, :organization)
      @agenda_items = AgendaItem.where(conversation: @conversations).includes(:deliverables, :conversation, :owner)
      @deliverables = Deliverable.where(parent_id: @agenda_items).includes(:parent, :owner, :assignee)
      @conversation_deliverables = Deliverable.where(parent_id: @conversations).includes(:parent, :owner, :assignee)

      render json: @organization,
             include: %w(organization_members, organization_members.member),
             meta: {
                 conversations: to_json_api(@conversations),
                 agenda_items: to_json_api(@agenda_items),
                 deliverables: to_json_api(@deliverables),
                 conversation_deliverables: to_json_api(@conversation_deliverables),
                 editable: policy(@organization).edit?
             }
    end

    def show_only_organization
      @organization = policy_scope(Organization).includes(organization_members: :member).find(params[:id])
      authorize @organization
      @conversations = policy_scope(Conversation)
                           .where(organization: @organization)
                           .includes(:conversation_members, :members, :organization)
      render json: @organization,
             include: %w(organization_members, organization_members.member),
             meta: {
                 editable: policy(@organization).edit?
             }
    end

    swagger_schema :OrganizationInput do
      key :required, [:organization]

      property :organization, type: :object do
        property :name, type: :string
      end
    end

    swagger_path '/organizations' do
      operation :post, security: [bearer: []] do
        key :operationId, 'createOrganization'
        key :summary, 'Create Organization'
        key :tags, ['organization']
        key :produces, ['application/json']

        parameter name: :organization, in: :body, required: true, description: 'Organization fields' do
          schema do
            key :'$ref', :OrganizationInput
          end
        end

        response 200 do
          key :description, 'Organization response'
          schema do
            key :'$ref', :responseOne_Organization
          end
        end

        response 422, description: 'Unprocessable Resource' do
          schema do
            key :'$ref', :errors
          end
        end

        response :default do
          key :description, 'Unexpected error'
        end
      end
    end
    
    def create
      @organization = current_user.organizations.create(organization_params.merge(owner: current_user))
      
      authorize @organization
      if @organization.save
        render json: @organization, serializer: OrganizationSerializer
      else
        render json: @organization, status: 422, serializer: ActiveModel::Serializer::ErrorSerializer
      end
    end
    
    swagger_path '/organizations/{id}' do
      operation :patch, security: [bearer: []] do
        key :summary, 'Update a specific Organization'
        key :description, 'Returns the all details for the organization overview'
        key :operationId, 'updateOrganizationById'
        key :tags, ['organization']
        key :produces, ['application/json']

        parameter name: :id, in: :path, type: :string, required: true
        
        parameter name: :organization, in: :body, required: true, description: 'Organization fields to update' do
          schema do
            key :'$ref', :OrganizationInput
          end
        end

        response 200 do
          key :description, 'Organization response'
          schema do
            key :'$ref', :responseOne_Organization
          end
        end

        response 422, description: 'Unprocessable Resource' do
          schema do
            key :'$ref', :errors
          end
        end

        response :default do
          key :description, 'Unexpected error'
        end
      end
    end
    
    def update
      authorize @organization

      if @organization.update(organization_update_params)
        render json: @organization, serializer: OrganizationSerializer
      else
        render json: @organization, status: 422, serializer: ActiveModel::Serializer::ErrorSerializer
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_organization
        @organization = Organization.find(params[:id])
        authorize @organization
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def organization_params
        params.require(:organization).permit(:name, :mission, :owner_id)
      end

      def organization_update_params
        params.require(:organization).permit(:name, :mission)
      end
  end
end

app/controllers/api/v1/organizations_controller.rb
module Api
  module V1
    class OrganizationsController < Base
      before_filter :authenticate_user!
      after_action :verify_authorized,    except: :index
      after_action :verify_policy_scoped, only: :index

      respond_to :json

      # GET /organizations.json
      def index
        @organizations = policy_scope(Organization).includes(:owner, :organization_members)
        @organizations = @organizations.includes(organization_members: :member) if params[:include] && params[:include].include?('organization_members.member')
        render json: @organizations, include: params[:include]
      end
      
      # GET /organizations/1.json
      def show
        # TODO: Remove that workaround when we switch to the final ActionCable release and can use connection-tokens
        # to build a list of connected connections per user and don't track the user as offline when he closes one of
        # his multiple browser windows. Then we can also remove that workaround.
        current_user.update presence_status: 'online'
        @organization = policy_scope(Organization).includes(:owner, :organization_members)
        @organization = @organization.includes(organization_members: :member) if params[:include] && params[:include].include?('organization_members.member')
        @organization = @organization.find(params[:id])
        authorize @organization
        current_user.update last_visited_organization: @organization

        render json: @organization,
               #include: %w(organization_members, organization_members.member),
               include: params[:include],
               meta: {
                 editable: policy(@organization).edit?
               }
      end
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= simple_form_for(@organization) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :mission
    - if @organization.persisted? && current_user == @organization.owner
      = f.input :owner_id, collection: @organization.members, include_blank: false
    - else
      = f.input :owner_id, as: :hidden

  .form-actions
    = f.button :submit, class: 'btn-info'
    - if @organization.persisted? && policy(@organization).destroy?
      = link_to @organization, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
        %i.fa.fa-trash-o
        Delete Organization
    = link_to 'Cancel',@organization,  class: 'btn btn-default'

app/views/organizations/edit.html.haml
%h3
  = link_to @organization, @organization, class: 'white-color'
  %i.fa.fa-angle-right
  Edit
%br

= render 'form'

app/views/organizations/index.html.haml
%h1 Listing organizations

%table.table
  %thead
    %tr
      %th Name
      %th Owner
      %th

  %tbody
    - @organizations.each do |organization|
      %tr
        %td= link_to organization.name, organization
        %td= organization.owner
        %td
          - if policy(organization).edit?
            = link_to 'Edit', edit_organization_path(organization)
        %td
          - if policy(organization).destroy?
            = link_to 'Destroy', organization, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
.form-container
  .form-root
    .form-logo
      = image_tag 'sizung-sigin-logo.png'
      
    .form-title
      New Organization
    = simple_form_for(@organization) do |f|
      = f.input :name, autofocus: true, label: 'Organization Name', required: false
      = f.button :submit, 'Create', class: 'form-button'
      = link_to "Cancel", root_path,  class: 'form-cancel-link', style: "margin-left: 10px;"

app/views/organizations/show.html.haml
= react_component('Root', {organizations: @organizations_json, users: @users_json, currentUser: {id: current_user.id, type: 'users'}}, {prerender: false} )

app/views/organizations/show_old.html.haml
%h3.organization-index-header.hover-container.white-color
  = @organization
  .hover-display-inline
    %small
      = link_to edit_organization_path(@organization), class: 'organization-hover-action' do
        %i.fa.fa-pencil
        edit
      = link_to organization_organization_members_path(@organization), class: 'organization-hover-action' do
        %i.fa.fa-users
        members

- deliverables = []
.col-xs-12.col-sm-6#conversation-column
  %h4.conversation-index-header.white-color
    %img{ src: "/icons/conversation-icon-white.png", height: '30px'}
    Conversations

    .organization-action.pull-right.hidden-xs.white-color
      = link_to new_organization_conversation_path(@organization), class: 'white-color' do
        %i.fa.fa-plus
        Add Conversation

  %h5.conversation-index-header.row.visible-xs.white-color
    .col-xs-12
      .pull-left
        = link_to new_organization_conversation_path(@organization), class: 'white-color' do
          %i.fa.fa-plus
          Add Conversation
      .pull-right
        %a#deliverables-link.white-color
          %img{ src: "/icons/deliverable-icon-white.png", height: '10px', style: 'margin: 5px;'}
          deliverables
          %i.fa.fa-chevron-right


  - @conversations.each do |conversation|
    - deliverables = deliverables | conversation.deliverables
    .conversation
      .conversation-header
        = react_component('UnseenBadge', {count: conversation.unseen_objects.where(user: current_user).count, selected: false}, {prerender: true} )
        .conversation-title
          = link_to conversation.title, conversation, { data: { no_turbolink: true } }
        .conversation-actions
          = link_to edit_conversation_path(conversation) do
            %i.fa.fa-pencil
            edit
          = link_to conversation, method: :delete, data: { :confirm => 'Are you sure?' } do
            %i.fa.fa-trash-o
            delete
      .conversation-conversation-object
        - last_conversation_object = conversation.conversation_objects.first
        - if last_conversation_object
          .conversation-conversation-object-owner
            - user = last_conversation_object.owner
            = react_component('User', {user: {email: user.email, firstName: user.first_name, lastName: user.last_name}}, {prerender: true})
          .conversation-conversation-object-title
            = last_conversation_object.title
        - else
          .conversation-empty
            Jump right in and start the conversation.

- deliverables = deliverables.select(&:due_on).sort_by(&:due_on) + deliverables.reject(&:due_on)

- if deliverables.select{ |deliverable| deliverable.assignee[:id] === current_user.id }.size > 0
  .hidden-xs.col-sm-6#deliverable-column
    .row
      %h4.deliverable-index-header.col-xs-6.col-sm-12.white-color
        %img{ src: "/icons/deliverable-icon-white.png", height: '20px', style: 'margin: 5px;'}
        My Deliverables

      %h5.col-xs-6.conversations-link.visible-xs.white-color
        .pull-right
          %a#conversations-link.white-color{ style: 'padding-top: 10px;'}
            %i.fa.fa-chevron-left
            conversations
            %img{ src: "/icons/conversation-icon-white.png", height: '20px'}


    - deliverables.each do |deliverable|
      - if deliverable and ( deliverable.assignee.id === current_user.id )
        .deliverable.row
          .deliverable-header.col-xs-12
            .deliverable-due-date.pull-right
              - if ( deliverable.due_on )
                - if ( deliverable.due_on <= Time.new )
                  %span.label.label-danger
                    = deliverable.due_on
                - else
                  %span.label.label-info
                    = deliverable.due_on
              - else
                = deliverable.due_on
            .deliverable-title.pull-left
              = link_to deliverable.title, "/conversations/#{deliverable.conversation.id}/agenda_items/#{deliverable.agenda_item.id}/deliverables/#{deliverable.id}", { data: { no_turbolink: true } }

          .deliverable-object.col-xs-12
            .deliverable-assignee
              - user = deliverable.assignee
              = react_component('User', {user: {email: user.email, firstName: user.first_name, lastName: user.last_name}}, {prerender: true})
            .deliverable-agenda-item-title
              %img{ src: "/icons/agenda-item-icon-gray.png", height: '12px', style: 'margin: 5px;'}
              = deliverable.agenda_item.title

%script{:type => "text/javascript"}
  :plain
    $('#deliverables-link').on(
        'click', function() {
        if ( $('#deliverable-column').length > 0 ) {
          $('#conversation-column').removeClass('col-xs-12');
          $('#conversation-column').addClass('hidden-xs');
          $('#deliverable-column').addClass('col-xs-12');
          $('#deliverable-column').removeClass('hidden-xs');
          }
    });
    $('#conversations-link').on(
        'click', function() {
          $('#deliverable-column').removeClass('col-xs-12');
          $('#deliverable-column').addClass('hidden-xs');
          $('#conversation-column').addClass('col-xs-12');
          $('#conversation-column').removeClass('hidden-xs');
    });