config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :api do

    # resources :time_tracks, only: [:index, :create, :update]
    post 'time_tracks', to: 'time_tracks#create'
    put 'time_tracks', to: 'time_tracks#update_last'

    concern :list_conversation_objects do |options|
      resources :conversation_objects, options.merge(only: [:index])
    end

    concern :unseen_objects do |options|
      delete 'unseen_objects', to: 'unseen_objects#destroy_all', defaults: options
      get 'unseen_objects', to: 'unseen_objects#index', defaults: options
      # resources :unseen_objects, options.merge(only: [:destroy_all])
    end

    concern :attachments do |options|
      resources :attachments, options.merge(only: [:new, :create])
    end

    resources :attachments, only: [:update]

    
    resources :organizations, shallow: true do
      concerns :unseen_objects, parent_type: 'Organization'

      resources :conversations do
        resources :agenda_items, only: [:index]
        concerns :list_conversation_objects, parent_type: 'Conversation'
        concerns :unseen_objects, parent_type: 'Conversation'
        concerns :attachments, parent_type: 'Conversation'
      end

      resources :organization_members, only: [:index, :create, :destroy]
    end

    resources :agenda_items, only: [:create, :show, :update] do
      concerns :list_conversation_objects, parent_type: 'AgendaItem'
      concerns :unseen_objects, parent_type: 'AgendaItem'
      concerns :attachments, parent_type: 'AgendaItem'
    end

    resources :deliverables, only: [:create, :show, :update] do
      concerns :list_conversation_objects, parent_type: 'Deliverable'
      concerns :unseen_objects, parent_type: 'Deliverable'
      concerns :attachments, parent_type: 'Deliverable'
    end

    resources :comments
    resources :conversation_members, only: [:create, :destroy]
    resources :organization_members, only: [:create, :update, :destroy]
    resources :meetings, only: [:create]
    resources :users, only: [:index, :create, :update], shallow: true do
      concerns :unseen_objects, parent_type: 'User'
    end
    resources :conversations, only: [:create, :update, :destroy]
    devise_scope :user do
      resources :session_tokens, only: [:create, :show]
      resources :long_lived_tokens, only: [:create]
    end
    resources :devices, only: [:create, :update]
  end

  resources :attachments, only: [:show]

  resources :organizations, shallow: true do
    resources :organization_members, only: [:index, :destroy]
    resources :conversations
  end

  get 'agenda_items/:id', to: 'react_routes#index', as: :agenda_item
  get 'deliverables/:id', to: 'react_routes#index', as: :deliverable
  get 'signup', to: 'react_routes#new_registration', as: :signup
  get 'organizations/:id/settings', to: 'react_routes#index', as: :settings
  get 'api/organizations/shallow/:id', to: 'api/organizations#show_only_organization'

  # Old routes are redirected to new shallow routes
  get 'conversations/:id/agenda_items/:agenda_item_id/deliverables/:deliverable_id', to: redirect('/deliverables/%{deliverable_id}')
  get 'conversations/:id/agenda_items/:agenda_item_id', to: redirect('/agenda_items/%{agenda_item_id}')

  # Route each error code to it's respective action in ErrorsController
  match '/404', :to => 'errors#not_found', :via => :all
  match '/422', :to => 'errors#unacceptable', :via => :all
  match '/500', :to => 'errors#internal_error', :via => :all

  devise_for :users, controllers: {
                       registrations: 'users/registrations',
                       sessions:      'users/sessions',
                       invitations:   'users/invitations'
                   }
  resources :samples, only: [:index]

  resources :apidocs, only: [:index]
  
  authenticated :user do
    root to: 'organizations#index', as: :authenticated_root
  end

  authenticate :user, lambda { |u| u.email == 'gugl@guenterglueck.com' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/websocket', to: ActionCable.server, via: [:get, :post]

  # root 'landing_page#index'
  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/views/layouts/_organizations_dropdown.haml
%ul.nav.dropdown-container
  %li.dropdown
    %a.organization-dropdown.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}, role: 'button',  aria_haspopup: 'true',  aria_expanded: 'false'}
      = @organization.try(:persisted?) ? @organization.name : 'Organizations'
      %span.caret
    %ul.dropdown-menu
      - policy_scope(Organization).each do |organization|
        - unless @organization.present? && @organization.id == organization.id
          %li
            = link_to organization.name, organization_path(organization) if organization.id
      %li.divider{role: 'separator'}
      %li
        = link_to new_organization_path do
          %i.fa.fa-plus
          %span Add new organization

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, user-scalable=no")
    %title= content_for?(:title) ? yield(:title) : "Sizung"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    = yield

    = javascript_include_tag "application", 'data-turbolinks-track' => false
    = javascript_include_tag "react_bundle", 'data-turbolinks-track' => false

    - if ENV['RAILS_ENV'] == 'development'
      = javascript_include_tag('http://localhost:4000/react-app-bundle.js')
      :javascript
        console.warn("Development mode. Make sure to start 'node devServer.js'");

app/views/layouts/conversation.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, user-scalable=no")
    %title= content_for?(:title) ? yield(:title) : "Sizung"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag "react_bundle", 'data-turbolinks-track' => false
    
    - if ENV['RAILS_ENV'] == 'development'
      = javascript_include_tag('http://localhost:4000/react-app-bundle.js')
      :javascript
        console.warn("Development mode. Make sure to start 'node devServer.js'");

  %body
    = yield